name: Validate

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: hacs/action@main
        with:
          category: integration

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.14"
      - name: Install
        run: uv pip install --system pytest-homeassistant-custom-component "pymodbus[serial]==3.13.1" foxess-modbus ruff mypy
      - name: Ruff
        run: ruff check . && ruff format --check .
      - name: Mypy
        run: mypy
      - name: Tests
        run: pytest
